### ISSUE TITLE
Make process flow

### ISSUE THREAD

**Issue by jantiend** [LCfP/Agent-Based-Auction-Model#9]
Including definitions (e.g. shippers, containers, shipments, consumer/destination, nodes, hubs).

**Comment by jantiend** [comment]
- Including definitions (e.g. shipment, container)

**Comment by N-Wouda** [comment]
A minor list (jargon),

| NL | ENG |
| --- | --- |
| Verkoper | Seller |
| Pakket(je) | Shipment |
| Veilingsmeester | Auctioneer |
| Bestemming | Destination |
| Klant | Consumer |
| Koper | Buyer |
| Container | Container |
| Verzender | Shipper |

@jantiend @CoertSchrijver
